app = "mia-searxng-redis"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
image = "flyio/redis:6.2.6"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[mounts]]
destination = "/data"
source = "persistance"
